#include "Bridge.hpp"
#include <print>

template<class... Ts> struct overloaded : Ts... { using Ts::operator()...; };

Bridge::Bridge(Backend& backend, QObject *parent) 
: QObject(parent), backend(backend)
{
    backend.toUIQueue.setCallback([this]{
        QMetaObject::invokeMethod(this, &Bridge::drainMessages, Qt::QueuedConnection);
    });
}

Bridge::~Bridge(){
    // Bridge is destroyed before Backend (declared after it in main), so the coordinator
    // thread is still running — unregister the callback so it can't call into a dead Bridge
    backend.toUIQueue.setCallback(nullptr);
}

void Bridge::drainMessages(){

    while (auto msg = backend.toUIQueue.dequeue()){

        std::visit(overloaded{
            [&](OutputTokensDelta& ot){ emit tokensReceived(ot.sid, QString::fromStdString(ot.delta)); },
            [&](ReasoningTokensDelta& rt){ emit reasoningReceived(rt.sid, QString::fromStdString(rt.delta)); },
            [&](EmitToolStarted& ts){ emit toolCallStarted(ts.sid, QString::fromStdString(ts.name)); },
            [&](EmitToolResult& tr){ emit toolCallFinished(tr.sid, tr.ok); },
            [&](SessionError& e){ emit responseError(e.sid, QString::fromStdString(e.msg)); },
            [&](TurnFinished& tf){ emit responseFinished(tf.sid); },
            [&](ListSessionsRes& ls){ emit sessionListReceived(std::move(ls.uuids)); },
        }, *msg);
    }
}

void Bridge::userPromptSent(Uuid id, const QString &content){
    backend.fromUIQueue.enqueue(PromptSubmission {
        .sid = id,
        .prompt = content.toStdString()
    });
}

// TODO: this should not take an id, they should be generated by the backend not frontend, fix later
void Bridge::sessionCreated(Uuid id){
    backend.fromUIQueue.enqueue(SessionCreation { .sid = id });
}

void Bridge::sessionsListRequested(){
    backend.fromUIQueue.enqueue(ListSessionsReq {});
}

void Bridge::sessionLoadRequested(Uuid id){
    backend.fromUIQueue.enqueue(LoadSessionReq { .sid = id });
}