#include "Bridge.hpp"
#include <print>

Bridge::Bridge(Backend& backend, QObject *parent) 
: QObject(parent), backend(backend)
{
    backend.toUIQueue.setCallback([this]{
        QMetaObject::invokeMethod(this, &Bridge::drainMessages, Qt::QueuedConnection);
    });
}

Bridge::~Bridge(){
    // Bridge is destroyed before Backend (declared after it in main), so the coordinator
    // thread is still running — unregister the callback so it can't call into a dead Bridge
    backend.toUIQueue.setCallback(nullptr);
}

void Bridge::drainMessages(){

    while (auto msg = backend.toUIQueue.dequeue()){
        switch (msg->kind){
            case toUIMessage::Kind::TURN_FINISHED:
                emit responseFinished(msg->session_id);
                break;

            case toUIMessage::Kind::ERROR:
                emit responseError(msg->session_id, QString::fromStdString(msg->content));
                break;

            case toUIMessage::Kind::OUTPUT_TOKENS:
                emit tokensReceived(msg->session_id, QString::fromStdString(msg->content));
                break;

            case toUIMessage::Kind::REASONING_TOKENS:
                emit reasoningReceived(msg->session_id, QString::fromStdString(msg->content));
                break;

            case toUIMessage::Kind::TOOL_CALL_STARTED:
                emit toolCallStarted(msg->session_id, QString::fromStdString(msg->content));
                break;

            case toUIMessage::Kind::TOOL_CALL_RESULT:
                emit toolCallFinished(msg->session_id, QString::fromStdString(msg->content));
                break;

            default:
                break;
        }
    }
}

void Bridge::userPromptSent(uint64_t id, const QString &content){
    fromUIMessage msg {
        .session_id = id,
        .kind = fromUIMessage::Kind::PROMPT_SUBMITED,
        .content = content.toStdString()
    };

    backend.fromUIQueue.enqueue(std::move(msg));
}

// TODO: this should not take an id, they should be generated by the backend not frontend, fix later
void Bridge::sessionCreated(uint64_t id){
    fromUIMessage msg {
        .session_id = id,
        .kind = fromUIMessage::Kind::CREATE_SESSION,
        .content = ""
    };

    backend.fromUIQueue.enqueue(std::move(msg));
}