#include "Bridge.hpp"
#include <print>

Bridge::Bridge(Backend& backend, QObject *parent) 
: QObject(parent), backend(backend)
{
    backend.toUIQueue.setCallback([this]{
        QMetaObject::invokeMethod(this, &Bridge::drainMessages, Qt::QueuedConnection);
    });
}

Bridge::~Bridge(){
    // Bridge is destroyed before Backend (declared after it in main), so the coordinator
    // thread is still running — unregister the callback so it can't call into a dead Bridge
    backend.toUIQueue.setCallback(nullptr);
}

void Bridge::drainMessages(){

    while (auto msg = backend.toUIQueue.dequeue()){
        switch (msg->kind){
            case toUIMessage::Kind::TURN_FINISHED: {
                emit responseFinished(msg->session_id);
                break;
            }
            case toUIMessage::Kind::ERROR: {
                auto str_cnt = std::get<std::string>(msg->content);
                emit responseError(msg->session_id, QString::fromStdString(str_cnt));
                break;
            }
            case toUIMessage::Kind::OUTPUT_TOKENS: {
                auto str_cnt = std::get<std::string>(msg->content);
                emit tokensReceived(msg->session_id, QString::fromStdString(str_cnt));
                break;
            }
            case toUIMessage::Kind::REASONING_TOKENS: {
                auto str_cnt = std::get<std::string>(msg->content);
                emit reasoningReceived(msg->session_id, QString::fromStdString(str_cnt));
                break;
            }
            case toUIMessage::Kind::TOOL_CALL_STARTED: {
                auto str_cnt = std::get<std::string>(msg->content);
                emit toolCallStarted(msg->session_id, QString::fromStdString(str_cnt));
                break;
            }
            case toUIMessage::Kind::TOOL_CALL_RESULT: {
                auto str_cnt = std::get<std::string>(msg->content);
                emit toolCallFinished(msg->session_id, QString::fromStdString(str_cnt));
                break;
            }
            case toUIMessage::Kind::LIST_SESSIONS_RES: {
                auto list = std::get<std::vector<Uuid>>(msg->content);
                emit sessionListReceived(std::move(list));
                break;
            }
            default: {
                break;
            }
        }
    }
}

void Bridge::userPromptSent(Uuid id, const QString &content){
    fromUIMessage msg {
        .session_id = id,
        .kind = fromUIMessage::Kind::PROMPT_SUBMITED,
        .content = content.toStdString()
    };

    backend.fromUIQueue.enqueue(std::move(msg));
}

// TODO: this should not take an id, they should be generated by the backend not frontend, fix later
void Bridge::sessionCreated(Uuid id){
    fromUIMessage msg {
        .session_id = id,
        .kind = fromUIMessage::Kind::CREATE_SESSION,
    };

    backend.fromUIQueue.enqueue(std::move(msg));
}

void Bridge::sessionsListRequested(){
    fromUIMessage msg {
        .kind = fromUIMessage::Kind::LIST_SESSIONS
    };

    backend.fromUIQueue.enqueue(std::move(msg));
}